# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2s0rdmuLTUbIcx6argONkluCRfZoaei

# Assignment 2

This assignment is about training and evaluating a POS tagger with some real data. The dataset is available through the Universal Dependencies (https://universaldependencies.org/) (UD) project. To get to know the project, please visit https://universaldependencies.org/introduction.html)
"""

import numpy as np
import  conllu 
from io import open
from conllu import parse_incr
from collections import defaultdict



"""**Part 1** (getting the data)

You can download the dataset files directly from the UD website, but it will let you only download all the languages in one compressed file. In this assignment you will be working with th GUM dataset, which you can download directly from:
https://github.com/UniversalDependencies/UD_English-GUM.
Please download it to your colab machine.


"""

# !git clone https://github.com/UniversalDependencies/UD_English-GUM

"""We will use the (train/dev/test) files:

UD_English-GUM/en_gum-ud-train.conllu

UD_English-GUM/en_gum-ud-dev.conllu

UD_English-GUM/en_gum-ud-test.conllu

They are all formatted in the conllu format. You may read about it [here](https://universaldependencies.org/format.html). There is a utility library **conllutils**, which can help you read the data into the memory. It has already been installed and imported above.

You should write a code that reads the three datasets into memory. You may choose the data structure by yourself. As you can see, every word is represented by a line, with columns representing specific features. We are only interested in the first and fourth columns, corresponding to the word and its POS tag.
"""

# Your code goes here
user = 'Or'
# Your code goes here
user = 'Or'
if user == 'Or':
    ud_dev = r"C:\MSC\NLP2\HW2\en_gum-ud-dev.csv"
    ud_train = r"C:\MSC\NLP2\HW2\en_gum-ud-train.csv"
    ud_test = r"C:\MSC\NLP2\HW2\en_gum-ud-test.csv"
    
else:
    ud_dev = r"C:\MSC\NLP2\HW2\UD_English-GUM\en_gum-ud-dev.conllu"
    ud_train = r"C:\MSC\NLP2\HW2\UD_English-GUM\en_gum-ud-train.conllu"
    ud_test = r"C:\MSC\NLP2\HW2\UD_English-GUM\en_gum-ud-test.conllu"


def read_conllu(path):
    "https://www.youtube.com/watch?v=lvJRFMvWtFI"
    # train data
    list_of_words  = []
    transition_conversion_list = []
    pos_tag_list = []
    idx = 0
    data_file = open(path, "r", encoding="utf-8")
    annotation = data_file.read()
    parse_annotation = conllu.parse(annotation)
    data_dict = defaultdict(lambda : defaultdict(dict))
    # item index
    item_idx = 1
    for item in parse_annotation:
        
        # get text tokens
        line_tokens = item.filter()
        
        
        # get token
        sentence_tokens = list(map(lambda x: x, line_tokens))
        
     
        # get meta data
        metadata = item.metadata
        text = metadata['text']
        
        # token index 
        i_token_idx = 0
        old_word = ''
        old_pos_tag = ''
        for i_token in sentence_tokens:
            
            if 'lemma' in i_token.keys():
                
                # get token line
                word = i_token['lemma']
                pos_tag =  i_token['upos']
                if i_token_idx != 0:
                    new_posible_key = old_pos_tag + '_' + pos_tag
                    if not new_posible_key in  data_dict[item_idx].keys():
                        data_dict[item_idx][new_posible_key] = 1
                    else:
                        data_dict[item_idx][new_posible_key] += 1
                    transition_conversion_list.append(new_posible_key)
                    pos_tag_list.append(pos_tag)
                    
                old_word = word
                old_pos_tag = pos_tag

                list_of_words.append(word)
                if not 'text' in  data_dict[item_idx].keys():
                    data_dict[item_idx]['text'] = text

                data_dict[item_idx][word] = pos_tag
            else:
                continue
            i_token_idx += 1
        item_idx += 1

    return data_dict, list_of_words, transition_conversion_list, pos_tag_list


def extract_ommision_matrix_B(train_df, unique_pos, unique_words):
    unique_words_list = unique_words.tolist()
    unique_pos_list = unique_pos.tolist()

    B = np.zeros([len(unique_pos), len(unique_words)])
    B_row_index = 0
    for i_pos in unique_pos:
        i_pos_train_df = train_df.loc[train_df['p'] == i_pos]
        i_pos_words, i_pos_word_count = np.unique(i_pos_train_df.loc[:, 'w'].values, return_counts=True)
        i_pos_percent = i_pos_word_count / np.sum(i_pos_word_count)
        i_pos_words_list = i_pos_words.tolist()
        for i_word in i_pos_words_list:
            if i_word in i_pos_words_list:
                word_index = i_pos_words_list.index(i_word)
                updated_percent_per_word_per_pos = i_pos_percent[word_index]
                B_column_word_index = unique_words_list.index(i_word)
                B[B_row_index, B_column_word_index] = updated_percent_per_word_per_pos
            else:
                continue
        B_row_index += 1

    return B


def generate_transition_matrix_A(train_df, unique_pos, unique_words):
    A = np.zeros([len(unique_pos), len(unique_pos)])
    rol_train_df = train_df.copy()
    rol_train_df = rol_train_df.iloc[np.arange(-1, len(rol_train_df) - 1)].reset_index(drop=True)
    rol_train_df = rol_train_df[1:]
    A_row_index = 0
    for i_pos in unique_pos:
        index_2_slice = (train_df['p'] == i_pos)
        index_2_slice = index_2_slice.iloc[np.arange(-1, len(index_2_slice) - 1)].reset_index(drop=True)
        index_2_slice.iloc[0] = False
        i_pos_train_df = train_df.loc[index_2_slice]

        i_pos_pos, i_pos_pos_count = np.unique(i_pos_train_df.loc[:, 'p'].values, return_counts=True)
        i_pos_percent = i_pos_pos_count / np.sum(i_pos_pos_count)
        i_pos_pos_list = i_pos_pos.tolist()
        for i_pos_next in i_pos_pos_list:
            if i_pos_next in i_pos_pos_list:
                pos_index = i_pos_pos_list.index(i_pos_next)
                updated_percent_per_pos_per_pos = i_pos_percent[pos_index]
                A_column_pos_index = unique_pos_list.index(i_pos_next)
                A[A_row_index, A_column_pos_index] = updated_percent_per_pos_per_pos
            else:
                continue
        A_row_index += 1
    return A





import pandas as pd


train_df = pd.read_csv(ud_train)
dev_df = pd.read_csv(ud_dev)
test_df = pd.read_csv(ud_test)


### Create matrices
pos_values = list(np.unique(train_df.loc[:, 'p'].values, return_counts=True))
unique_words = np.unique(train_df.loc[:, 'w'].values)
unique_pos= pos_values[0]
unique_words_list  = unique_words.tolist()
unique_pos_list  = unique_pos.tolist()


B = extract_ommision_matrix_B(train_df, unique_pos, unique_words)
A = generate_transition_matrix_A(train_df, unique_pos, unique_words)

a=5
def sentences_from_df(df):
    sentences = []
    sentence_ind = 1
    sentence = []

    for i in range(df.shape[0]):
        curr_sentence_ind = df.index[i][0]
        if curr_sentence_ind != sentence_ind:
            sentences.append(str.join(" ", sentence))
            sentence_ind += 1
            sentence = []
        sentence.append(df.iloc[i, :]['w'])

    return sentences


sentences = sentences_from_df(train_df)


#     pass
import operator
import nltk



# ______________________________________________________________________________________________________________________________________
"""**Part 2**

Write a class **simple_tagger**, with methods *train* and *evaluate*. The method *train* receives the data as a list of sentences, and use it for training the tagger. In this case, it should learn a simple dictionary that maps words to tags, defined as the most frequent tag for every word (in case there is more than one most frequent tag, you may select one of them randomly). The dictionary should be stored as a class member for evaluation.

The method *evaluate* receives the data as a list of sentences, and use it to evaluate the tagger performance. Specifically, you should calculate the word and sentence level accuracy.
The evaluation process is simply going word by word, querying the dictionary (created by the train method) for each word’s tag and compare it to the true tag of that word. The word-level accuracy is the number of successes divided by the number of words. For OOV (out of vocabulary, or unknown) words, the tagger should assign the most frequent tag in the entire training set (i.e., the mode). The function should return the two numbers: word level accuracy and sentence level accuracy.

"""

class simple_tagger:
  def train(self, data):
      # TODO
      return 
    
  
  def evaluate(self, data):
      # TODO
      return

"""**Part 3**

Similar to part 2, write the class hmm_tagger, which implements HMM tagging. The method *train* should build the matrices A, B and Pi, from the data as discussed in class. The method *evaluate* should find the best tag sequence for every input sentence using he Viterbi decoding algorithm, and then calculate the word and sentence level accuracy using the gold-standard tags. You should implement the Viterbi algorithm in the next block and call it from your class.

Additional guidance:
1. The matrix B represents the emissions probabilities. Since B is a matrix, you should build a dictionary that maps every unique word in the corpus to a serial numeric id (starting with 0). This way columns in B represents word ids.
2. During the evaluation, you should first convert each word into it’s index and then create the observation array to be given to Viterbi, as a list of ids. OOV words should be assigned with a random tag. To make sure Viterbi works appropriately, you can simply break the sentence into multiple segments every time you see an OOV word, and decode every segment individually using Viterbi.

"""

class hmm_tagger:
  def train(self, data):
      # TODO

      return 

  def evaluate(self, data):
      # TODO
      return 

# Viterbi
def viterbi (observations, A, B, Pi):
    best_sequence = None
    #...
    
    return best_sequence

# A simple example to run the Viterbi algorithm:
#( Same as in presentation "NLP 3 - Tagging" on slide 35)

# A = np.array([[0.3, 0.7], [0.2, 0.8]])
# B = np.array([[0.1, 0.1, 0.3, 0.5], [0.3, 0.3, 0.2, 0.2]])
# Pi = np.array([0.4, 0.6])
# print(viterbi([0, 3, 2, 0], A, B, Pi))
# Expected output: 1, 1, 1, 1

"""**Part 4**

Compare the results obtained from both taggers and a MEMM tagger, implemented by NLTK (a known NLP library), over both, the dev and test datasets. To train the NLTK MEMM tagger you should execute the following lines (it may take some time to train...):
"""

from nltk.tag import tnt 

tnt_pos_tagger = tnt.TnT()
tnt_pos_tagger.train(train_data)
print(tnt_pos_tagger.evaluate(test_data))

"""Print both, word level and sentence level accuracy for all the three taggers in a table."""

# Your code goes here