# -*- coding: utf-8 -*-
"""Assignment 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2s0rdmuLTUbIcx6argONkluCRfZoaei

# Assignment 2

This assignment is about training and evaluating a POS tagger with some real data. The dataset is available through the Universal Dependencies (https://universaldependencies.org/) (UD) project. To get to know the project, please visit https://universaldependencies.org/introduction.html)
"""

import numpy as np
import  conllu 
from io import open
from conllu import parse_incr
from collections import defaultdict
import pandas as pd



"""**Part 1** (getting the data)

You can download the dataset files directly from the UD website, but it will let you only download all the languages in one compressed file. In this assignment you will be working with th GUM dataset, which you can download directly from:
https://github.com/UniversalDependencies/UD_English-GUM.
Please download it to your colab machine.


"""

# !git clone https://github.com/UniversalDependencies/UD_English-GUM

"""We will use the (train/dev/test) files:

UD_English-GUM/en_gum-ud-train.conllu

UD_English-GUM/en_gum-ud-dev.conllu

UD_English-GUM/en_gum-ud-test.conllu

They are all formatted in the conllu format. You may read about it [here](https://universaldependencies.org/format.html). There is a utility library **conllutils**, which can help you read the data into the memory. It has already been installed and imported above.

You should write a code that reads the three datasets into memory. You may choose the data structure by yourself. As you can see, every word is represented by a line, with columns representing specific features. We are only interested in the first and fourth columns, corresponding to the word and its POS tag.
"""

# Your code goes here
user = 'Or'
# Your code goes here
user = 'Or'
if user == 'Or':
    ud_dev = r"C:\MSC\NLP2\HW2\en_gum-ud-dev.csv"
    ud_train = r"C:\MSC\NLP2\HW2\en_gum-ud-train.csv"
    ud_test = r"C:\MSC\NLP2\HW2\en_gum-ud-test.csv"
    
else:
    ud_dev = r"C:\MSC\NLP2\HW2\UD_English-GUM\en_gum-ud-dev.conllu"
    ud_train = r"C:\MSC\NLP2\HW2\UD_English-GUM\en_gum-ud-train.conllu"
    ud_test = r"C:\MSC\NLP2\HW2\UD_English-GUM\en_gum-ud-test.conllu"



def extract_ommision_matrix_B(train_df, unique_pos, unique_words):
    unique_words_list = unique_words.tolist()
    unique_pos_list = unique_pos.tolist()

    B = np.zeros([len(unique_pos), len(unique_words)])
    B_row_index = 0
    for i_pos in unique_pos:
        i_pos_train_df = train_df.loc[train_df['p'] == i_pos]
        i_pos_words, i_pos_word_count = np.unique(i_pos_train_df.loc[:, 'w'].values, return_counts=True)
        i_pos_percent = i_pos_word_count / np.sum(i_pos_word_count)
        i_pos_words_list = i_pos_words.tolist()
        for i_word in i_pos_words_list:
            if i_word in i_pos_words_list:
                word_index = i_pos_words_list.index(i_word)
                updated_percent_per_word_per_pos = i_pos_percent[word_index]
                B_column_word_index = unique_words_list.index(i_word)
                B[B_row_index, B_column_word_index] = updated_percent_per_word_per_pos
            else:
                continue
        B_row_index += 1

    return B


def generate_transition_matrix_A(train_df, unique_pos, unique_words):
    unique_words_list  = unique_words.tolist()
    unique_pos_list  = unique_pos.tolist()
    A = np.zeros([len(unique_pos), len(unique_pos)])
    rol_train_df = train_df.copy()
    rol_train_df = rol_train_df.iloc[np.arange(-1, len(rol_train_df) - 1)].reset_index(drop=True)
    rol_train_df = rol_train_df[1:]
    A_row_index = 0
    for i_pos in unique_pos:
        index_2_slice = (train_df['p'] == i_pos)
        index_2_slice = index_2_slice.iloc[np.arange(-1, len(index_2_slice) - 1)].reset_index(drop=True)
        index_2_slice.iloc[0] = False
        i_pos_train_df = train_df.loc[index_2_slice]

        i_pos_pos, i_pos_pos_count = np.unique(i_pos_train_df.loc[:, 'p'].values, return_counts=True)
        i_pos_percent = i_pos_pos_count / np.sum(i_pos_pos_count)
        i_pos_pos_list = i_pos_pos.tolist()
        for i_pos_next in i_pos_pos_list:
            if i_pos_next in i_pos_pos_list:
                pos_index = i_pos_pos_list.index(i_pos_next)
                updated_percent_per_pos_per_pos = i_pos_percent[pos_index]
                A_column_pos_index = unique_pos_list.index(i_pos_next)
                A[A_row_index, A_column_pos_index] = updated_percent_per_pos_per_pos
            else:
                continue
        A_row_index += 1
    return A





def get_list_of_sentences_tag_lists(df):
    word_index_array = df['i'].to_numpy()
    initial_sentence_idx = np.where(word_index_array == 1)[0]
    words_list = df['w'].to_list()
    tag_list = df['p'].to_list()

    sentence_list  = (initial_sentence_idx.size-1)*['None']
    sentence_tag_list  = (initial_sentence_idx.size-1)*['None']

    for sentence_idx in range(initial_sentence_idx.size-1):
        curr_sentence =  words_list[initial_sentence_idx[sentence_idx]:initial_sentence_idx[sentence_idx+1]]
        curr_tag =  tag_list[initial_sentence_idx[sentence_idx]:initial_sentence_idx[sentence_idx+1]]

        
        sentence_list[sentence_idx] = curr_sentence
        sentence_tag_list[sentence_idx] = curr_tag

    return sentence_list, sentence_tag_list


def sentences_from_df(df):
    sentences = []
    sentence_ind = 1
    sentence = []
    
    
        
    for i in range(df.shape[0]):
        if not 's' in df.columns:
            curr_sentence_ind = df.index[i][0]
        else:
            curr_sentence_ind = df.iloc[i]['s']

        if curr_sentence_ind != sentence_ind:
            sentences.append(str.join(" ", sentence))
            sentence_ind += 1
            sentence = []
        sentence.append(df.iloc[i, :]['w'])

    return sentences



class simple_tagger:
    def __init__(self):
        self.tagger = {}
    
    def train(self, data):
        pos = np.unique(data['p'], return_counts=True)
        most_frequent_pos = pos[0][np.where(pos[1] == max(pos[1]))][0]

        tagger = defaultdict(lambda: most_frequent_pos)

        unique_words = np.unique(data.loc[:, 'w'].values)
        for word in unique_words:
            word_data = data.loc[data['w'] == word]
            word_data_count = word_data['p'].value_counts()
            predicted_tag = word_data_count.index[0]
            # predicted_tag = pos_of_word = np.unique(data.loc[data['w'] == word, 'p'], return_counts=True)
            tagger[word] = predicted_tag

        self.tagger = tagger
    def evaluate(self, data):
        # sentences = sentences_from_df(data)
        sentences_list, sentence_tag_list = get_list_of_sentences_tag_lists(data)

        words_success = 0
        sentences_success = 0
        idx = pd.IndexSlice
        for sentence_num, (sentence, sentence_tags) in enumerate(zip(sentences_list, sentence_tag_list)):
        # for sentence_num, sentence in enumerate(sentences, 1):
            count_successes = 0
            # sentence_df = data.loc[idx[sentence_num], 'p'].values
            for word_num, (word, actual_tag) in enumerate(zip(sentence, sentence_tags)):
            # for word_num, word in enumerate(sentence.split(' ')):
                preducted_tag = self.tagger[word]
                # actual_tag = sentence_df[word_num]

                if preducted_tag == actual_tag:
                    words_success += 1
                    count_successes += 1

            if count_successes == len(sentence)-1:
                sentences_success += 1

        word_accuracy = round(words_success / data.shape[0] * 100, 4)
        sentence_accuracy = round(sentences_success / len(sentences_list) * 100, 4)

        return word_accuracy, sentence_accuracy
    
    
    




train_df = pd.read_csv(ud_train)
dev_df = pd.read_csv(ud_dev)
test_df = pd.read_csv(ud_test)




# sentences1 = sentences_from_df(train_df)

sentences, tag = get_list_of_sentences_tag_lists(train_df)

tagger = simple_tagger()
tagger.train(train_df)


simple_tagger_word_accuracy_train, simple_tagger_sentence_accuracy_train = tagger.evaluate(train_df)
simple_tagger_word_accuracy_dev, simple_tagger_sentence_accuracy_dev = tagger.evaluate(dev_df)
simple_tagger_word_accuracy_test, simple_tagger_sentence_accuracy_test = tagger.evaluate(test_df)


result_list = [['train' ,simple_tagger_word_accuracy_train, simple_tagger_sentence_accuracy_train],
['dev', simple_tagger_word_accuracy_dev, simple_tagger_sentence_accuracy_dev],
['test', simple_tagger_word_accuracy_test, simple_tagger_sentence_accuracy_test]]

simple_tagger_results =  pd.DataFrame(result_list, columns = ['data-set', 'word-accuracy[%]', 'sentence-accuracy[%]'])
simple_tagger_results.head()
# print(f'train data: word accuracy = {simple_tagger_word_accuracy_train}%, sentence accuracy = {simple_tagger_sentence_accuracy_train}%')
# print(f'dev data: word accuracy = {simple_tagger_word_accuracy_dev}%, sentence accuracy = {simple_tagger_sentence_accuracy_dev}%')
# print(f'test data: word accuracy = {simple_tagger_word_accuracy_test}%, sentence accuracy = {simple_tagger_sentence_accuracy_test}%')


a=5 
#     pass
# import operator
# import nltk


# ______________________________________________________________________________________________________________________________________
"""**Part 2**

Write a class **simple_tagger**, with methods *train* and *evaluate*. The method *train* receives the data as a list of sentences, and use it for training the tagger. In this case, it should learn a simple dictionary that maps words to tags, defined as the most frequent tag for every word (in case there is more than one most frequent tag, you may select one of them randomly). The dictionary should be stored as a class member for evaluation.

The method *evaluate* receives the data as a list of sentences, and use it to evaluate the tagger performance. Specifically, you should calculate the word and sentence level accuracy.
The evaluation process is simply going word by word, querying the dictionary (created by the train method) for each word’s tag and compare it to the true tag of that word. The word-level accuracy is the number of successes divided by the number of words. For OOV (out of vocabulary, or unknown) words, the tagger should assign the most frequent tag in the entire training set (i.e., the mode). The function should return the two numbers: word level accuracy and sentence level accuracy.

"""

# tagger = simple_tagger()
# tagger.train(train_df)

# # https://piazza.com/class/klxc3m1tzqz2o8?cid=40 - "You should evaluate on the test and dev datasets separately. The train file is for training only"
# simple_tagger_word_level_accuracy_train, simple_tagger_sentence_level_accuracy_train = tagger.evaluate(train_df)
# simple_tagger_word_level_accuracy_test, simple_tagger_sentence_level_accuracy_test = tagger.evaluate(test_df)
# simple_tagger_word_level_accuracy_dev, simple_tagger_sentence_level_accuracy_dev = tagger.evaluate(dev_df)


# print(f'*train* data: word accuracy = {simple_tagger_word_level_accuracy_train} %, sentence accuracy = {simple_tagger_sentence_level_accuracy_train} %')
# print(f'*test* data: word accuracy = {simple_tagger_word_level_accuracy_test} %, sentence accuracy = {simple_tagger_sentence_level_accuracy_test} %')
# print(f'*dev* data: word accuracy = {simple_tagger_word_level_accuracy_dev} %, sentence accuracy = {simple_tagger_sentence_level_accuracy_dev} %')


"""**Part 3**

Similar to part 2, write the class hmm_tagger, which implements HMM tagging. The method *train* should build the matrices A, B and Pi, from the data as discussed in class. The method *evaluate* should find the best tag sequence for every input sentence using he Viterbi decoding algorithm, and then calculate the word and sentence level accuracy using the gold-standard tags. You should implement the Viterbi algorithm in the next block and call it from your class.

Additional guidance:
1. The matrix B represents the emissions probabilities. Since B is a matrix, you should build a dictionary that maps every unique word in the corpus to a serial numeric id (starting with 0). This way columns in B represents word ids.
2. During the evaluation, you should first convert each word into it’s index and then create the observation array to be given to Viterbi, as a list of ids. OOV words should be assigned with a random tag. To make sure Viterbi works appropriately, you can simply break the sentence into multiple segments every time you see an OOV word, and decode every segment individually using Viterbi.

"""


### Create matrices
pos_values = list(np.unique(train_df.loc[:, 'p'].values, return_counts=True))
unique_words = np.unique(train_df.loc[:, 'w'].values)
unique_pos= pos_values[0]
unique_words_list  = unique_words.tolist()
unique_pos_list  = unique_pos.tolist()


# B = extract_ommision_matrix_B(train_df, unique_pos, unique_words)
# A = generate_transition_matrix_A(train_df, unique_pos, unique_words)
# pi_initial_matrix = np.ones([unique_pos.size,1])*(1/unique_pos.size)

# get_list_of_sentences(train_df)
def wordsToIdx(words, B_columns):
    columns_as_list = list(B_columns)
    wordsAsIdxSegment = []
    
    for word in words:
        wordsAsIdxSegment.append(columns_as_list.index(word))

    return wordsAsIdxSegment


def segmentOfWordsToSentencePrediction(self, segment, sentencePredict, last=False):
    if segment:
        segmentIdx = wordsToIdx(segment, self.B.columns)
        segmentPredict = viterbi(segmentIdx, self.A, self.B, self.Pi)
        sentencePredict += segmentPredict

    if not last:
        random_tag = np.random.choice(self.A.index)
        sentencePredict.append(random_tag)




class hmm_tagger:
    data = pd.DataFrame()
    A = []
    B = []
    Pi = []
    uniqueWordsArr = []
    
    def __init__(self, data_df):
        
        unique_pos, pos_counts = list(np.unique(data_df.loc[:, 'p'].values, return_counts=True))
        unique_words, word_counts = np.unique(data_df.loc[:, 'w'].values, return_counts=True)
        unique_words_list  = unique_words.tolist()
        unique_pos_list  = unique_pos.tolist()
        
        self.data_df = data_df
        self.unique_pos = unique_pos
        self.unique_words = unique_words
        self.unique_words_list = unique_words_list
        self.unique_pos_list = unique_pos_list



    def train(self):

        data_df = self.data_df
        unique_pos = self.unique_pos
        unique_words = self.unique_words
        
        
        B = extract_ommision_matrix_B(self.data_df, unique_pos, unique_words)
        A = generate_transition_matrix_A(self.data_df, unique_pos, unique_words)
        Pi = np.ones([unique_pos.size,1])*(1/unique_pos.size)

        
        self.A = A
        self.B = B
        self.Pi = Pi
        
        

    def evaluate(self, data):
        
        # get data 
        data_df = self.data_df
        
        # initiate the amount of hits
        words_hits = 0
        
        # number of sentences in which all words are correctly classified
        sentence_hits = 0 
        
        number_of_words_with_duplicates = len(data_df['w'])
        
        sentence_list, sentence_tag_list = get_list_of_sentences_tag_lists(data_df)

        # run on all sentences 
        for index, (sentence, sentence_tags) in enumerate(zip(sentence_list, sentence_tag_list)):
            # check for every word and sentence's accuracy
            
            # initiate the amounts of hits per sentence
            sentence_hits = 0
            sentenceIdx = []
            
            # this loop run on all words in sentence fror predicting

            for word in sentence:
                
                if word in self.unique_words:
                    wordIdx = list(self.B).index(word)
                    sentenceIdx.append(wordIdx)
                else:
                    randomTagIdx = np.random.randint(len(self.uniqueWordsArr))
                    sentenceIdx.append(randomTagIdx)

                sentencePredict = viterbi(sentenceIdx, self.A, self.B, self.Pi)
            
            # this loop run on all words in sentence fror evaluating predicting
            for word_idx, (word, actual_tag) in enumerate(zip(sentence, sentence_tags)):
                
                
                # get predicting tag
                predicted_tag = sentencePredict[word_idx]

                
                # check if the predicited tag is equal to GT    
                if actual_tag == predicted_tag:
                    sentence_hits += 1

            words_hits += sentence_hits

            if words_hits == len(sentence):
                sentence_hits += 1
        
        
        word_level_accuracy = round(words_hits / number_of_words_with_duplicates *100, 4)
        sentence_level_accuracy = round(sentence_hits / len(sentence_list) *100, 4)

        return word_level_accuracy, sentence_level_accuracy


def findBestTag(delta_df, t):
    maxValue = 0
    bestTag = ''

    for tag in delta_df.index:
        currentValue =delta_df.loc[tag, t]
        
        if currentValue > maxValue:
            maxValue = currentValue
            bestTag = tag
    
    return bestTag




# Viterbi
def viterbi (observations, A, B, Pi):
    #...
    # creates variables
    delta_df = pd.DataFrame(index=B.index, columns=np.arange(len(observations))).fillna(0) 
    psi_df = pd.DataFrame(index=B.index, columns=np.arange(len(observations))).fillna(0)
    best_sequence = [0]*len(observations)

    firstObserv = observations[0]
    listOfWords = list(B.columns)
    firstObservWord = listOfWords[firstObserv]

    # initializtion step
    for tag in delta_df.index:
        b = B.loc[tag, firstObservWord]
        delta_df.loc[tag, 0] = b*Pi[tag]
        psi_df.loc[tag, 0] = 0

    # iteration step
    for observIdx, currentObserv in enumerate(observations[1:], 1):
        currentObservWord = listOfWords[currentObserv]
        valuesToTakeMax = []

        maxValue = 0
        bestTagForMaxValue = ''

        for tag in delta_df.index:
            b = B.loc[tag, currentObservWord]

            for tag2 in delta_df.index:
                currentValue = delta_df.loc[tag2, observIdx-1] * A.loc[tag2, tag]

            if currentValue > maxValue:
                maxValue = currentValue
                bestTagForMaxValue = tag2
        delta_df.loc[tag, observIdx] = maxValue*b
        psi_df.loc[tag, observIdx] = bestTagForMaxValue


    # sequence recovery
    t = len(observations)-1
    best_sequence[t] = findBestTag(delta_df, t)

    for t in range(len(observations)-2, -1, -1):
        best_sequence[t] = psi_df.loc[best_sequence[t+1], t+1]

    return best_sequence


hmmTagger = hmm_tagger()


hmmTagger.train(train_df)

hmm_word_level_accuracy_test, hmm_sentence_level_accuracy_test = hmmTagger.evaluate(test_df)
hmm_word_level_accuracy_dev, hmm_sentence_level_accuracy_dev = hmmTagger.evaluate(dev_df)

print(f'*test* data: word accuracy = {hmm_word_level_accuracy_test} %, sentence accuracy = {hmm_sentence_level_accuracy_test} %')
print(f'*dev* data: word accuracy = {hmm_word_level_accuracy_dev} %, sentence accuracy = {hmm_sentence_level_accuracy_dev} %')



# A simple example to run the Viterbi algorithm:
#( Same as in presentation "NLP 3 - Tagging" on slide 35)

# A = np.array([[0.3, 0.7], [0.2, 0.8]])
# B = np.array([[0.1, 0.1, 0.3, 0.5], [0.3, 0.3, 0.2, 0.2]])
# Pi = np.array([0.4, 0.6])
# print(viterbi([0, 3, 1, 0], A, B, Pi))
# Expected output: 1, 1, 1, 1

# A simple example to run the Viterbi algorithm:
#( Same as in presentation "NLP 3 - Tagging" on slide 35)

# A = np.array([[0.3, 0.7], [0.2, 0.8]])
# B = np.array([[0.1, 0.1, 0.3, 0.5], [0.3, 0.3, 0.2, 0.2]])
# Pi = np.array([0.4, 0.6])
# print(viterbi([0, 3, 2, 0], A, B, Pi))
# Expected output: 1, 1, 1, 1

"""**Part 4**

Compare the results obtained from both taggers and a MEMM tagger, implemented by NLTK (a known NLP library), over both, the dev and test datasets. To train the NLTK MEMM tagger you should execute the following lines (it may take some time to train...):
"""

from nltk.tag import tnt 

tnt_pos_tagger = tnt.TnT()
tnt_pos_tagger.train(train_data)
print(tnt_pos_tagger.evaluate(test_data))

"""Print both, word level and sentence level accuracy for all the three taggers in a table."""

# Your code goes here